### ISSUE TITLE
Data not rendering in browser

### ISSUE THREAD

**Issue by jessleenyc** [jessleenyc/wiki#2]
Hi @annarankin !

I'm trying to get some data to render in the browser but it looks like my server or browser isn't recognizing it because what's rendering is an empty hash. I used binding.pry to go into my server file, and it has all the data from my seed file but it's not showing up. I recall this happening in class during the 200cupid example but I can't remember what the fix is. This is a pretty big blocker for me.

Thanks!

**Comment by annarankin** [comment]
Hey Jess! Which routes/views are you working with?

**Comment by jessleenyc** [comment]
Server FIle: ```    get '/' do @articles = Category.first 
erb :index
    end```
index.erb: ``` <h1> <%= @articles %> </h1>```

I thought the server file wasn't recognizing the Category class when I utilized binding.pry it recognized it just fine. The erb file is connect properly because I see a #hashtag rendered. Am I blanking on something?

**Comment by annarankin** [comment]
Hey Jess, sorry for the late reply - were you able to get this sorted? Erb will render that hashtag to represent a single instance of an object - if you call a method on it - `.cat_name` - then it'll return whatever that attribute's value is.

**Comment by annarankin** [comment]
Aha - just looked at your `index.erb`, looks like you sorted it!
