### ISSUE TITLE
BLOCKED: updated seed data and entire application is returning an error

### ISSUE THREAD

**Issue by jessleenyc** [jessleenyc/wiki#3]
Hi @annarankin, 

I changed the title of an article in my seed data, reran the schema & updated seedata and now my entire application is broken. Undid the chnage, reran schema & reseeded and it's still breaking. 

Error:
```Couldn't find Author with 'id'=3```

This is the first time i've reseeded my data since deploying on heroku earlier today. Can you please help me figure out this bug?

Thanks!

**Comment by annarankin** [comment]
Hey Jess, when you're seeding your database, you don't need to include a `password_digest` - only a `password` field. For example:

```ruby
authors = [
  {username: "Bot1", password_digest: "$2a$10$/sA9kGnlrbbZnQcq/stfWu.U1RDS/eFboCGDL0bkS9f246R8xxsQK"},
  {username: "Bot2", password_digest: "$2a$10$/sA9kGnlrbbZnQcq/stfWu.U1RDS/eFboCGDL0bkS9f246R8xxsQK"},
  {username: "Bot3", password_digest: "$2a$10$/sA9kGnlrbbZnQcq/stfWu.U1RDS/eFboCGDL0bkS9f246R8xxsQK"},
]
```
should be:

```ruby
authors = [
  {username: "Bot1", password: "blah"},
  {username: "Bot2", password: "blah"},
  {username: "Bot3", password: "blah"},
]
```

**Comment by jessleenyc** [comment]
@annarankin THANK YOU.

**Comment by annarankin** [comment]
:v: :raised_hands: :+1:
